---
version: 0.0.1
metadata:
  code: EXAMPLE-RESTQA
  name: Example Restqa
  description: Delicious Microservice example maintained with RestQA
tests:
  local:
    port: 8887
    command: npm run dev
    data: {}
  performance:
    tool: artillery
    outputFolder: tests/performances
    onlySuccess: false
specification:
  tool: swagger

