---
version: 0.0.1
metadata:
  code: EXAMPLE-RESTQA
  name: example-restqa
  description: Delicious Microservice maintained with RestQA
tests:
  local:
    port: 8000
    command: npm run dev
  performance:
    tool: artillery
    outputFolder: tests/performances
    onlySuccess: false
specification:
  tool: swagger
