version: 0.0.1
metadata:
  code: JSON-PLACEHOLDER
  name: jsonplaceholder from typecode
  description: An example application to demo RestQA Features
resqta:
  dashboard:
    editable: true
environments:
  - name: local
    default: true
    plugins:
      - name: "@restqa/restqapi"
        config:
          url: https://jsonplaceholder.typicode.com
    outputs:
      - type: html
        enabled: true
      - type: file
        enabled: true
        config:
          path: restqa-result.json
