{
 "title": "RestQa",
 "description": "Automation Test dashboard",
 "tags": [
  "restqa ",
  "autiomation testing"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n# RestQa - Open Automation Testing Platform\n\nFor some help: [https://github.com/restqa](https://github.com/restqa)\n\n\n\n",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suite Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "startTime",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "name.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "id.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "env.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "total",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "passed",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "failed",
       "id": "8",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "duration",
       "id": "9",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "type.keyword: \"testSuite\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suite Total",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "testSuite filter",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suite Passed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "test suite success filter",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success: true",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suites passed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "test suite failed filter",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success: false",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suite Result",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success : true",
     "timeField": "timestamp"
    },
    {
     "alias": "faliure",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success : false",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Test Suite Trend Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success: true",
     "timeField": "timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"testSuite\" AND success: false",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Duration time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "1h", "min_doc_count": 1, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "duration",
       "id": "1",
       "meta": {},
       "pipelineAgg": "select metric",
       "pipelineVariables": [
        { "name": "var1", "pipelineAgg": "select metric" }
       ],
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "type.keyword : \"testSuite\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total features",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword : \"feature\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Features Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 26 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"feature\" AND result : true",
     "timeField": "timestamp"
    },
    {
     "alias": "Failed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"feature\" AND result : false",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Feature table",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "feature_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "total",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "passed",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "failed",
       "id": "4",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "skipped",
       "id": "5",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "undefined",
       "id": "6",
       "meta": {},
       "settings": {},
       "type": "sum"
      },
      {
       "field": "duration",
       "id": "7",
       "meta": {},
       "settings": {},
       "type": "max"
      }
     ],
     "query": "type.keyword: \"feature\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Scenario Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 45 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "alias": "Passed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"scenario\" AND status.keyword: \"passed\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Failed",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"scenario\" AND status.keyword: \"failed\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Skipped",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"scenario\" AND status.keyword: \"skipped\"",
     "timeField": "timestamp"
    },
    {
     "alias": "Undefined",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "type.keyword: \"scenario\" AND status.keyword: \"undefined\"",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}