ignore: 
  urls:
  - https://github.com/restqa/generator-plugin
  - https://linkedin.com/company/restqa
  - https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
  - https://twitter.com/restqa
  - https://cucumber.io/*

delay:
  'https://github.com': 500
