env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:jest/style
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
rules:
  no-control-regex: 0
globals:
  JestQA: true
