const Plugin = require("@restqa/plugin");
const Config = require("../config");
const {CUSTOM_STEP_FILE_NAME} = require("../services/custom-step-definition");

const jestqa = new JestQA(__filename, true);

beforeEach(jestqa.beforeEach);
afterEach(jestqa.afterEach);

describe("#bootstrap", () => {
  test("Throw error if the processor is undefined", () => {
    const Bootstrap = require("./bootstrap");
    expect(() => {
      Bootstrap();
    }).toThrow(
      new Error(
        "Please provide a processor containing the methods: After, AfterAll, Before, BeforeAll, Given, When, Then, defineParameterType, setWorldConstructor and setDefaultTimeout."
      )
    );
  });

  test("Throw error if the processor doesn't contain an required method", () => {
    const Bootstrap = require("./bootstrap");
    expect(() => {
      Bootstrap({
        After: jest.fn()
      });
    }).toThrow(
      new Error(
        "Please provide a processor containing the methods: After, AfterAll, Before, BeforeAll, Given, When, Then, defineParameterType, setWorldConstructor and setDefaultTimeout."
      )
    );

    expect(() => {
      Bootstrap({
        After: jest.fn(),
        AfterAll: jest.fn(),
        Before: jest.fn(),
        BeforeAll: jest.fn(),
        Given: jest.fn(),
        When: jest.fn(),
        Then: jest.fn(),
        defineParameterType: jest.fn()
      });
    }).toThrow(
      new Error(
        "Please provide a processor containing the methods: After, AfterAll, Before, BeforeAll, Given, When, Then, defineParameterType, setWorldConstructor and setDefaultTimeout."
      )
    );
  });

  test("Throw error if the config can't be loaded", () => {
    const Bootstrap = require("./bootstrap");
    expect(() => {
      Bootstrap({
        After: jest.fn(),
        AfterAll: jest.fn(),
        Before: jest.fn(),
        BeforeAll: jest.fn(),
        Given: jest.fn(),
        When: jest.fn(),
        Then: jest.fn(),
        defineParameterType: jest.fn(),
        setWorldConstructor: jest.fn(),
        setDefaultTimeout: jest.fn()
      });
    }).toThrow(new Error("The configuration is not loaded"));
  });

  test("Load plugin @restqa/plugin-rest-api then run setup the processor", () => {
    const content = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  local:
    port: 8088
    command: npm run dev
    data:
      storage: "./test/data"
      channel: google-sheet
      config: 
        id: test
        apikey: testapi
      variables:
        hello: world

`;
    const filename = jestqa.createTmpFile(content, ".restqa.yml");

    const mockPlugin = new Plugin("plugin-rest-api");
    mockPlugin.addGivenStep("my step", () => {}, "my description", "example");
    mockPlugin.addState("host", "https://example.com");
    jest.mock("@restqa/plugin-rest-api", () => mockPlugin);

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(filename);
    const options = {
      config,
      isLocalTest: true
    };

    const Bootstrap = require("./bootstrap");

    Bootstrap(processor, options);

    expect(mockPlugin._getConfig()).toEqual({
      url: "http://127.0.0.1:8088"
    });

    expect(processor.Given).toHaveBeenCalledTimes(1);
    expect(processor.Given).toHaveBeenCalledWith(
      "my step",
      expect.any(Function),
      "my description",
      ["plugin-rest-api", "example"]
    );

    expect(processor.defineParameterType).toHaveBeenCalledTimes(1);

    expect(processor.setWorldConstructor).toHaveBeenCalledTimes(1);
    const World = processor.setWorldConstructor.mock.calls[0][0];
    const world = new World({});
    expect(world.state.host).toBe("https://example.com");
    expect(world.data.get("{{ hello }}")).toBe("world");
    expect(world.getConfig("plugin-rest-api")).toEqual({
      url: "http://127.0.0.1:8088"
    });

    const {regexp, transformer, name} =
      processor.defineParameterType.mock.calls[0][0];
    expect(regexp).toEqual(/\{\{(.*)\}\}/);
    expect(name).toEqual("data");
    expect(transformer.call(world, "hello")).toEqual("world");

    expect(jestqa.getLoggerMock()).toHaveBeenCalledTimes(1);
    expect(jestqa.getLoggerMock().mock.calls[0][0]).toMatch(
      '🎯 The selected environment is: "local"'
    );
  });

  test("Load plugin @restqa/plugin-rest-api then run setup the processor (integration tests)", () => {
    const content = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  integrations:
  - name: UAT 
    url: https://uat.example.com
    data:
      storage: "./test/data"
      channel: google-sheet
      config: 
        id: test
        apikey: testapi
      variables:
        hello: world

`;
    const filename = jestqa.createTmpFile(content, ".restqa.yml");

    const mockPlugin = new Plugin("plugin-rest-api");
    mockPlugin.addGivenStep("my step", () => {}, "my description", "example");
    jest.mock("@restqa/plugin-rest-api", () => mockPlugin);

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(filename);
    const options = {
      config,
      isLocalTest: false,
      env: "uat"
    };

    const Bootstrap = require("./bootstrap");

    Bootstrap(processor, options);

    expect(mockPlugin._getConfig()).toEqual({
      url: "https://uat.example.com"
    });

    expect(processor.Given).toHaveBeenCalledTimes(1);
    expect(processor.Given).toHaveBeenCalledWith(
      "my step",
      expect.any(Function),
      "my description",
      ["plugin-rest-api", "example"]
    );

    expect(processor.defineParameterType).toHaveBeenCalledTimes(1);

    expect(processor.setWorldConstructor).toHaveBeenCalledTimes(1);
    const World = processor.setWorldConstructor.mock.calls[0][0];
    const world = new World({});
    expect(world.data.get("{{ hello }}")).toBe("world");
    expect(world.getConfig("plugin-rest-api")).toEqual({
      url: "https://uat.example.com"
    });

    const {regexp, transformer, name} =
      processor.defineParameterType.mock.calls[0][0];
    expect(regexp).toEqual(/\{\{(.*)\}\}/);
    expect(name).toEqual("data");
    expect(transformer.call(world, "hello")).toEqual("world");

    expect(jestqa.getLoggerMock()).toHaveBeenCalledTimes(1);
    expect(jestqa.getLoggerMock().mock.calls[0][0]).toMatch(
      '🎯 The selected environment is: "UAT"'
    );
  });

  test("Load plugin plugin-rest-api and restqkube then run setup the processor (+ setup the timeout)", () => {
    const content = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  integrations:
  - name: local
    url: https://api.restqa.io
    data:
      startSymbol: '[['
      endSymbol: ']]'
      variables:
        foo: bar
    outputs:
      - type: html
        enabled: true
plugins:
  - name: restqkube
    config:
      kube:
        config: ./kubeconfig
settings:
  timeout: 10000
    `;
    const filename = jestqa.createTmpFile(content, ".restqa-example.yml");

    const mockPlugins = [
      new Plugin("plugin-rest-api")
        .addGivenStep("my given step", () => {})
        .addState("host", "https://example.com"),
      new Plugin("restqkube")
        .addThenStep("my then step", () => {})
        .addState("cluster", "example.cluster.local")
    ];

    jest.mock("@restqa/plugin-rest-api", () => mockPlugins[0]);

    jest.mock("module", () => {
      return {
        createRequire: () => {
          return function (config) {
            return mockPlugins[1];
          };
        }
      };
    });

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(filename);
    const options = {
      config,
      isLocalTest: false,
      env: "local"
    };

    const Bootstrap = require("./bootstrap");

    Bootstrap(processor, options);

    expect(processor.Before).toHaveBeenCalledTimes(2);

    expect(processor.Before).toHaveBeenCalledWith(expect.any(Function));
    expect(processor.Before).toHaveBeenLastCalledWith(
      {tags: "@skip or @wip"},
      expect.any(Function)
    );

    expect(mockPlugins[0]._getConfig()).toEqual({
      url: "https://api.restqa.io"
    });

    expect(processor.Given).toHaveBeenCalledTimes(1);
    expect(processor.Given).toHaveBeenCalledWith(
      "my given step",
      expect.any(Function),
      undefined,
      ["plugin-rest-api"]
    );

    expect(mockPlugins[1]._getConfig()).toEqual({
      kube: {
        config: "./kubeconfig"
      }
    });

    expect(processor.Then).toHaveBeenCalledTimes(1);
    expect(processor.Then).toHaveBeenCalledWith(
      "my then step",
      expect.any(Function),
      undefined,
      ["restqkube"]
    );

    expect(processor.setDefaultTimeout).toHaveBeenCalledTimes(1);
    expect(processor.setDefaultTimeout).toHaveBeenCalledWith(10000);

    expect(processor.setWorldConstructor).toHaveBeenCalledTimes(1);
    const World = processor.setWorldConstructor.mock.calls[0][0];
    const world = new World({});
    expect(world.state.host).toBe("https://example.com");
    expect(world.data.get("[[ foo ]]")).toBe("bar");

    expect(processor.defineParameterType).toHaveBeenCalledTimes(1);
    const {regexp, transformer, name} =
      processor.defineParameterType.mock.calls[0][0];
    expect(regexp).toEqual(/\[\[(.*)\]\]/);
    expect(name).toEqual("data");
    expect(transformer.call(world, "foo")).toEqual("bar");

    expect(jestqa.getLoggerMock()).toHaveBeenCalledTimes(1);
    expect(jestqa.getLoggerMock().mock.calls[0][0]).toMatch(
      '🎯 The selected environment is: "local"'
    );
  });

  test("Throw error if we want to run an integration test but the integration config is missing", () => {
    const content = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  local:
    port: 8080
    command: npm run dev
    `;
    const filename = jestqa.createTmpFile(content, ".restqa.yml");

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(filename);
    const options = {
      config,
      isLocalTest: false,
      env: "uat"
    };

    const Bootstrap = require("./bootstrap");

    expect(() => {
      Bootstrap(processor, options);
    }).toThrow(
      new Error(
        "The integration test can't be executed due to missing integration test configuration"
      )
    );
  });

  test("Throw error if we want to run an unt test but the local config is missing", () => {
    const content = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  integrations:
    - name: UAT
      url: https://uat.example.com
    `;
    const filename = jestqa.createTmpFile(content, ".restqa.yml");

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(filename);
    const options = {
      config,
      isLocalTest: true
    };

    const Bootstrap = require("./bootstrap");

    expect(() => {
      Bootstrap(processor, options);
    }).toThrow(
      new Error(
        "The local test can't be executed due to missing local test configuration"
      )
    );
  });

  test("Load custom definition then run setup the processor", () => {
    const contentConfig = `
---
version: 0.0.1
metadata:
  code: APP
  name: app
  description: Configuration generated by restqa init
tests:
  local:
    port: 8088
    command: npm run dev
`;
    const configFilename = jestqa.createTmpFile(contentConfig, ".restqa.yml");

    const contentCustomStep = `
module.exports = function ({ Given, When, Then }) {
  Given ('custom given step', () => {})
  When ('custom when step', () => {})
  Then ('custom then step', () => {})
}
`;
    jestqa.createTmpFile(contentCustomStep, `tests/${CUSTOM_STEP_FILE_NAME}`);

    const mockCwd = jestqa.getTmpFolder();
    jest.mock("../utils/process.js", () => {
      return {
        cwd: mockCwd
      };
    });

    const mockPlugin = new Plugin("plugin-rest-api");
    mockPlugin.addGivenStep("my step", () => {}, "my description", "example");
    mockPlugin.addState("host", "https://example.com");
    jest.mock("@restqa/plugin-rest-api", () => mockPlugin);

    const processor = {
      After: jest.fn(),
      AfterAll: jest.fn(),
      Before: jest.fn(),
      BeforeAll: jest.fn(),
      Given: jest.fn(),
      When: jest.fn(),
      Then: jest.fn(),
      defineParameterType: jest.fn(),
      setWorldConstructor: jest.fn(),
      setDefaultTimeout: jest.fn()
    };

    const config = new Config();
    config.load(configFilename);
    const options = {
      config,
      isLocalTest: true
    };

    const Bootstrap = require("./bootstrap");

    Bootstrap(processor, options);

    expect(mockPlugin._getConfig()).toEqual({
      url: "http://127.0.0.1:8088"
    });

    expect(processor.Given).toHaveBeenCalledTimes(2);
    expect(processor.Given.mock.calls[0]).toEqual([
      "my step",
      expect.any(Function),
      "my description",
      ["plugin-rest-api", "example"]
    ]);
    expect(processor.Given.mock.calls[1]).toEqual([
      "custom given step",
      expect.any(Function)
    ]);

    expect(processor.When).toHaveBeenCalledTimes(1);
    expect(processor.When.mock.calls[0]).toEqual([
      "custom when step",
      expect.any(Function)
    ]);

    expect(processor.Then).toHaveBeenCalledTimes(1);
    expect(processor.Then.mock.calls[0]).toEqual([
      "custom then step",
      expect.any(Function)
    ]);

    expect(processor.defineParameterType).toHaveBeenCalledTimes(1);

    expect(processor.setWorldConstructor).toHaveBeenCalledTimes(1);
  });
});
