const YAML = require('yaml')
const fs = require('fs')
const path = require('path')
//const inquirer = require('inquirer')

module.exports = async function (program) {
  let filename = path.resolve(process.cwd(), '.restqa.yml')
  let  content = {}
  if (true === program.y) {
    content = getDefaultTemplate()
  }

  let contentYAML = YAML.stringify(content,null, { directivesEndMarker: true })
  fs.writeFileSync(filename, contentYAML)
}

function getDefaultTemplate() {
  return {
    version: '0.0.1',
    metadata: {
      code: 'APP',
      name: 'sample api app',
      description: 'Configuration generated by restqa init -y'
    },
    environments: [{
      name: 'local',
      default: true,
      plugins: [{
        name: 'restqapi',
        config: {
          url: 'https://api.restqa.io'
        }
      }],
      outputs: [{
        type: 'http-html-report',
        enabled: true
      }]
    }]
  }
}
