version: 0.0.1
metadata:
  code: RESTQA-EXAMPLE-SCENARIO-04-REQUEST-QUERY-STRING
  name: "@restqa/example-scenario-04-request-query-string"
  description: Boilerplate for scenario
tests:
  local:
    port: "8887"
    command: npm run dev
