version: 0.0.1
metadata:
  code: RESTQA-EXAMPLE-SCENARIO-05-REQUEST-JSONBODY
  name: "@restqa/example-scenario-05-request-jsonbody"
  description: Boilerplate for scenario
tests:
  local:
    port: "8887"
    command: "node index.js"
    data: 
      storage:  './tests/storage'
