version: 0.0.1
metadata:
  code: RESTQA-SCREENSHOT
  name: "@restqa/screenshot"
  description: A way to create screenshot of the RestQA Report UI
tests:
  local:
    port: "8887"
    command: npm run test:server
