version: 0.0.1
metadata:
  code: RESTQA-EXAMPLE-SCENARIO-03-REQUEST-AUTHORIZATION
  name: "@restqa/example-scenario-03-request-authorization"
  description: Example scenario to demonstrate how to use Request authorization
tests:
  local:
    port: "8887"
    command: npm run dev
