version: 0.0.1
metadata:
  code: RESTQA-EXAMPLE-SCENARIO-01-REQUEST-HOST
  name: "@restqa/example-scenario-01-request-host"
  description: Boilerplate for scenario
tests:
  local:
    port: "8887"
    command: npm run dev
