version: 0.0.1
metadata:
  code: RESTQA-EXAMPLE-SCENARIO-06-REQUEST-FORMDATA
  name: "@restqa/example-scenario-06-request-formdata"
  description: Boilerplate for scenario form data
tests:
  local:
    port: "8887"
    command: npm run dev
