version: 0.0.1
metadata:
  code: TYPESCRIPT
  name: typescript
  description: Delicious Microservice maintained with RestQA
tests:
  local:
    port: "8088"
    command: ts-node -r tsconfig-paths/register src/index
